// Code generated by MockGen. DO NOT EDIT.
// Source: services/favorite_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/alkosmas92/platform-go-challenge/internal/app/models"
	gomock "github.com/golang/mock/gomock"
)

// MockFavoriteService is a mock of FavoriteService interface.
type MockFavoriteService struct {
	ctrl     *gomock.Controller
	recorder *MockFavoriteServiceMockRecorder
}

// MockFavoriteServiceMockRecorder is the mock recorder for MockFavoriteService.
type MockFavoriteServiceMockRecorder struct {
	mock *MockFavoriteService
}

// NewMockFavoriteService creates a new mock instance.
func NewMockFavoriteService(ctrl *gomock.Controller) *MockFavoriteService {
	mock := &MockFavoriteService{ctrl: ctrl}
	mock.recorder = &MockFavoriteServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavoriteService) EXPECT() *MockFavoriteServiceMockRecorder {
	return m.recorder
}

// CreateFavorite mocks base method.
func (m *MockFavoriteService) CreateFavorite(ctx context.Context, favorite *models.Favorite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFavorite", ctx, favorite)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFavorite indicates an expected call of CreateFavorite.
func (mr *MockFavoriteServiceMockRecorder) CreateFavorite(ctx, favorite interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFavorite", reflect.TypeOf((*MockFavoriteService)(nil).CreateFavorite), ctx, favorite)
}

// DeleteFavorite mocks base method.
func (m *MockFavoriteService) DeleteFavorite(ctx context.Context, userID, assetID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFavorite", ctx, userID, assetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFavorite indicates an expected call of DeleteFavorite.
func (mr *MockFavoriteServiceMockRecorder) DeleteFavorite(ctx, userID, assetID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFavorite", reflect.TypeOf((*MockFavoriteService)(nil).DeleteFavorite), ctx, userID, assetID)
}

// GetFavoritesByUserID mocks base method.
func (m *MockFavoriteService) GetFavoritesByUserID(ctx context.Context, userID string, limit, offset int) ([]*models.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoritesByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*models.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoritesByUserID indicates an expected call of GetFavoritesByUserID.
func (mr *MockFavoriteServiceMockRecorder) GetFavoritesByUserID(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoritesByUserID", reflect.TypeOf((*MockFavoriteService)(nil).GetFavoritesByUserID), ctx, userID, limit, offset)
}

// UpdateFavorite mocks base method.
func (m *MockFavoriteService) UpdateFavorite(ctx context.Context, userID, assetID string, favorite *models.Favorite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFavorite", ctx, userID, assetID, favorite)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFavorite indicates an expected call of UpdateFavorite.
func (mr *MockFavoriteServiceMockRecorder) UpdateFavorite(ctx, userID, assetID, favorite interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFavorite", reflect.TypeOf((*MockFavoriteService)(nil).UpdateFavorite), ctx, userID, assetID, favorite)
}
